### ISSUE TITLE
Add documentation for all functions and add necessary tooling to catch these errors.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#334]

**Comment by krishnasrinivas** [comment]
@harshavardhana 
* as a priority, the commit has comments for only exposed APIs, I will add comments to the rest of the functions as a lower priority. we can keep the bug open.
* Also I will change the commenting style so that we can use tools like https://github.com/jsdoc2md/jsdoc-to-markdown or https://github.com/cbou/markdox
