### ISSUE TITLE
api: check ram usage for putObject()

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio-js#428]

**Comment by brendanashworth** [comment]
This issue might just have to be decked because of the way Amazon requires multipart uploads to work. The node process [must buffer until the `partSize` for the chunk](https://github.com/minio/minio-js/blob/9a44f63967be5f1649be57297274914fa9d3b937/src/main/minio.js#L1036), which for larger files can be a quite serious chunk of RAM (~525MB), although only 5MB for small objects. There is no way to get out of this buffering, afaik.

One alternative is to, instead of keeping the buffered data in RAM, we can offload it into a file as the stream finishes the chunk. However this beats around the bush and will probably cause more performance issues than already exist, most especially for fast-moving streams.

CPU-wise, there are a few improvements to be made (profiling indicates [this](https://github.com/minio/minio-js/blob/9a44f63967be5f1649be57297274914fa9d3b937/src/main/minio.js#L362) takes up a chunk of runtime), but because the *vast, vast* majority of time is spent on the wire and in networking, optimizations in that department would be moot.

I'm not sure exactly how to significantly improve RAM usage in `putObject`, simply because Amazon requires that we buffer data so significantly.

**Comment by harshavardhana** [comment]
> I'm not sure exactly how to significantly improve RAM usage in putObject, simply because Amazon requires that we buffer data so significantly.

This bug is here to evaluate what are impacts of uploading with large files and an average memory usage.  Wee have agreed some time ago that 525M uploading per part serially is not a problem. We are talking about 525MB for a 5TB single object which is usually really rare. 

That is why this github issue is not a bug but a question for which we need answers.  minio-go now defaults to single part size to 64MB, we can potentially bump this value here as well depending on the understanding of overall memory usage in nodejs runtime.

**Comment by brendanashworth** [comment]
> depending on the understanding of overall memory usage in nodejs runtime

Ah, I see. I'll do some profiling to see where exactly the memory usage is coming from. Probably v8/the runtime will take the cheese for why it uses more memory than go but profiling should answer the question definitively.

**Comment by krishnasrinivas** [comment]
@brendanashworth this is what you can do, upload 50G file to play.minio.io using putObject and subsequently fPutObject, and check how RAM usage increases using `htop` for both the APIs and at what point it stabilizes.

**Comment by krishnasrinivas** [comment]
Memory usage is stable. Just verified.
