### ISSUE TITLE
copyObject -- source and dest

### ISSUE THREAD

**Issue by luhkevin** [minio/minio-js#560]
Your copy object function is defined as:

`copyObject(bucketName, objectName, sourceObject, conditions, callback)`

Why is the source after the destination? In most file/object copy-related APIs that I'm aware of, it's always `src dst`, not `dst src`. E.g. the Unix `copy` command, as well as most AWS S3 utilities.

**Comment by harshavardhana** [comment]
copyObject is not the representation of a CLI. An API is a mnemocode here. 

For example x86 assembly uses `mnemocode destination, source`, like `mov ah, 17h`. In school we learn that `y = 17 * x`, and when speaking we say `y is 17 times x`.  And in most (natural) languages, the subject comes before the verb. So again, `y is 17 times x`.  But at the same time, if you move a box, you say, `move this box over there next to the wall`. In that case, the source `"what" = subject` is first, and the destination second.

So here the choice was former than the latter since copyObject() is function of source and destination in the same way as `y = 17 * x`  - now for any utility tools like unix copy, `mc`, `s3cmd` latter is a well defined choice.

**Comment by krishnasrinivas** [comment]
@luhkevin we use `copy dst src` consistently across our client libs (python, java etc). Closing this issue.
