### ISSUE TITLE
Failed to return err in statObject to check file exist

### ISSUE THREAD

**Issue by christtrc** [minio/minio-js#565]
I use statObject to check whether file exists on minio server,  if the file to be checked does not exist,   the callback `(err, stat) => {}` was not called.

**Comment by krishnasrinivas** [comment]
@christtrc can you paste your code? because it works for me.

**Comment by christtrc** [comment]
I just use the code from [https://docs.minio.io/docs/javascript-client-api-reference#statObject](https://docs.minio.io/docs/javascript-client-api-reference#statObject)
```
minioClient.statObject('mybucket', 'photo.jpg', function(err, stat) {
  if (err) {
    return console.log(err)
  }
  console.log(stat)
})
```
If the bucket exist but the file does not exist, two `console.log` output nothing, but get a 404 error info on chrome debug console.

**Comment by krishnasrinivas** [comment]
@christtrc for access from browser you should be using presigned get/put/post operations. Here's the presigned-get API: https://docs.minio.io/docs/javascript-client-api-reference#presignedGetObject

Any reason you are using minio client library directly in the browser? How are you using minio client in the browser? you will have to use `yarn browserify` to generate minio-browser.js and then use it in the browser like this: https://github.com/minio/minio-js/blob/master/examples/get-object.html Are you using it in a similar fashion? Because statObject works as expected for me in browser as well.

**Comment by christtrc** [comment]
@krishnasrinivas Thanks! 

In my project, i use minio as my artifacts repository. My project is an admin backend programmed by react.js which use minio js client library to store files to or retrieve files from the repo.   I just use the same as the example demo code, maybe something is wrong with react.js, i will check it.

**Comment by deekoder** [comment]
@christtrc is this issue resolved for you? Please let us know we can close this issue.

**Comment by krishnasrinivas** [comment]
> In my project, i use minio as my artifacts repository. My project is an admin backend programmed by react.js which use minio js client library to store files to or retrieve files from the repo. I just use the same as the example demo code, maybe something is wrong with react.js, i will check it.

@christtrc we'll close this let us know if you still have problems.

Also for your usecase you will still have to use presigned-PUT/GET operations and not use minio-js in your browser app directly.

**Comment by harshavardhana** [comment]
> @christtrc we'll close this let us know if you still have problems.
> 
> Also for your usecase you will still have to use presigned-PUT/GET operations and not use minio-js in your browser app directly.

Closing.
