### ISSUE TITLE
Progress Bar for File upload and download?

### ISSUE THREAD

**Issue by athithrao** [minio/minio-js#740]
Hello, 

I would like to know if there is an API that returns the upload/download progress. 

Thank you.

**Comment by kannappanr** [comment]
@athithrao We do not have any API that returns progress. But what we do in our browser code is to use presigned urls to upload/download objects.
https://docs.minio.io/docs/javascript-client-api-reference.html#presignedGetObject
https://docs.minio.io/docs/javascript-client-api-reference.html#presignedPutObject

You can use `http client` in javascript to track progress. An example is given here  https://www.sitepoint.com/html5-javascript-file-upload-progress-bar/

**Comment by deekoder** [comment]
@athithra,  since this can be done completely on the application side, adding this to the SDK won't be valuable. If you share code with us on our slack channel we can help you on the application side. I will go ahead and close this as won't fix. If you feel we need to discuss this further, please feel free to reactivate.
