### ISSUE TITLE
updating from 7.0.10 to 7.0.11 causes fputobject to hang on big files

### ISSUE THREAD

**Issue by dottgonzo** [minio/minio-js#788]
after updating minio client from 7.0.10 to 7.0.11, if i try to upload (with fputobject) big files (80MB), it hangs while upload the file. contextually i've upgraded the node version from 10.16.0 to 10.16.1, but i think that the issues is caused from the minio library. Tomorrow i will say something more

**Comment by kanagarajkm** [comment]
This has happened due to upgrading `async` to latest (v3.1.0) https://github.com/minio/minio-js/pull/785/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34

`async.whilst` is changed compared to older version, an example is here
https://caolan.github.io/async/v3/docs.html#whilst

fPutObject uses the older style(https://github.com/caolan/async/blob/v1.5.2/README.md#whilst) of calling `async.whilst` which led multipart not starting.
https://github.com/minio/minio-js/blob/master/src/main/minio.js#L959
But async.whilst expects the test function to be like
```js
function test(cb) { cb(null, count < 5;) },

//or

cb => { cb(null, count < 5) },
``` 

Looks like multipart is not covered in the functional tests, we should add it.

**Comment by dottgonzo** [comment]
you just noticed the problem and i can confirm that our software works downgrading minio from 7.0.10 to 7.0.11 with the same library context and node version
