### ISSUE TITLE
minio-js ipv6 - family option

### ISSUE THREAD

**Issue by dcversus** [minio/minio-js#801]
https://github.com/minio/minio-js/blob/master/src/main/minio.js#L155
https://nodejs.org/api/http.html#http_class_http_agent

i want pass `family` param, but pick create problems for it(
mb rm pick here? why we need pick it?

**Comment by kannappanr** [comment]
@dcversus Will take a look and get back to you

**Comment by kaankabalak** [comment]
@dcversus Based on the discussion on #685, the main reason why we used `_.pick` here was that we explicitly wanted the user to be able to pass only certain request options, as otherwise it might've caused the minio-js calls to fail on faulty configurations.

Currently, it is not possible to pass a `family` parameter, however we will work on adding the option to pass it on the `setRequestOptions` method.
