### ISSUE TITLE
why listobjects return prefix with profix[0]

### ISSUE THREAD

**Issue by liujingjie** [minio/minio-js#879]
i use listObjects to show the files and the folders,
```
  var stream = minioClient.listObjects("first", "f11/", false);
    stream.on("data", function(obj) {
      console.log(obj);
    });
```
But I only got the first letter of the folder，
![image](https://user-images.githubusercontent.com/9113753/100958741-d9f3ea00-3557-11eb-8158-095f5f484246.png)

and the actual files are 
![image](https://user-images.githubusercontent.com/9113753/100960047-7ae3a480-355a-11eb-8e01-be07d3ab4fbb.png)

i found the code in `xml-parsers.js` and the prefix get ondy first letter.why not return all the Prefix

![image](https://user-images.githubusercontent.com/9113753/100960134-aa92ac80-355a-11eb-9269-35eadf96705a.png)

**Comment by ebozduman** [comment]
@liujingjie ,

If you don't mind, can you test and verify the fix, #877, one more time for your scenario?
I refactored the code to address some other similar issues and I cannot reproduce your case to test in my environment. I appreciate your help.

**Comment by liujingjie** [comment]
I saw #877  before, and modified my code according to it。now my code is 
```
if (xmlobj.CommonPrefixes) {
          if (!Array.isArray(xmlobj.CommonPrefixes)) {
            xmlobj.CommonPrefixes = Array(xmlobj.CommonPrefixes);
          }
          xmlobj.CommonPrefixes.forEach(function(commonPrefix) {
            var prefix = commonPrefix.Prefix;
            var size = 0;
            result.objects.push({
              prefix,
              size
            });
          });
        }
```

and i can get the full prefix

**Comment by ebozduman** [comment]
@liujingjie ,

Yes. That's what was needed in your case.
The problem was if the parsed value is a single item, the new xml parser package was not returning it in the expected type/format: an array with a single element. Instead a single entity, like a string, was returned.
Since there were other similar issues, I put them all in one PR. So, you'll see more than what you needed in #877 PR changes. There will be a new minio-js release very  soon, within a week or two. You can pick it up and you don't have to do anything manually.
